
## Push Buttons [B3 : B0]
# Pressed is 1, not pressed is 0.
set_property PACKAGE_PIN U12 [get_ports {BRAKE}]
set_property PACKAGE_PIN V12 [get_ports {RIGHT}]
set_property PACKAGE_PIN U7  [get_ports {LEFT}]
set_property PACKAGE_PIN Y6  [get_ports {RESET}]
set_property IOSTANDARD LVCMOS33 [get_ports {BRAKE}]
set_property IOSTANDARD LVCMOS33 [get_ports {RIGHT}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEFT}]
set_property IOSTANDARD LVCMOS33 [get_ports {RESET}]


## Seven Segment Display Pins.
# Bus order is: [7:0] = [abcdefg, dp]
# Display pins are active LOW; logic 0 turns them on.
set_property PACKAGE_PIN J20 [get_ports {sseg_an[3]}]
set_property PACKAGE_PIN J18 [get_ports {sseg_an[2]}]
set_property PACKAGE_PIN H20 [get_ports {sseg_an[1]}]
set_property PACKAGE_PIN K19 [get_ports {sseg_an[0]}]
set_property PACKAGE_PIN K20 [get_ports ssegout[0]]
set_property PACKAGE_PIN L19 [get_ports ssegout[1]]
set_property PACKAGE_PIN H18 [get_ports ssegout[2]]
set_property PACKAGE_PIN M20 [get_ports ssegout[3]]
set_property PACKAGE_PIN K21 [get_ports ssegout[4]]
set_property PACKAGE_PIN K18 [get_ports ssegout[5]]
set_property PACKAGE_PIN H17 [get_ports ssegout[6]]
set_property PACKAGE_PIN H19 [get_ports ssegout[7]]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ssegout[0]]
set_property IOSTANDARD LVCMOS33 [get_ports ssegout[1]]
set_property IOSTANDARD LVCMOS33 [get_ports ssegout[2]]
set_property IOSTANDARD LVCMOS33 [get_ports ssegout[3]]
set_property IOSTANDARD LVCMOS33 [get_ports ssegout[4]]
set_property IOSTANDARD LVCMOS33 [get_ports ssegout[5]]
set_property IOSTANDARD LVCMOS33 [get_ports ssegout[6]]
set_property IOSTANDARD LVCMOS33 [get_ports ssegout[7]]


## LEDs [LED7 : LED0]
# LEDs are active HIGH, logic 1 turns them on.
set_property PACKAGE_PIN Y9  [get_ports {LC}]
set_property PACKAGE_PIN Y8  [get_ports {LB}]
set_property PACKAGE_PIN V7  [get_ports {LA}]
set_property PACKAGE_PIN W12 [get_ports {RA}]
set_property PACKAGE_PIN W11 [get_ports {RB}]
set_property PACKAGE_PIN V8  [get_ports {RC}]
set_property IOSTANDARD LVCMOS33 [get_ports {LC}]
set_property IOSTANDARD LVCMOS33 [get_ports {LB}]
set_property IOSTANDARD LVCMOS33 [get_ports {LA}]
set_property IOSTANDARD LVCMOS33 [get_ports {RA}]
set_property IOSTANDARD LVCMOS33 [get_ports {RB}]
set_property IOSTANDARD LVCMOS33 [get_ports {RC}]